name: Backpacks
version: ${project.version}
main: gg.steve.elemental.bps.Backpacks
api-version: 1.13
authors: [stevegoodhill]
description: Virtual backpacks plugin for ElementalMC
depend:
  - Pets
  - ElementalTokens
softdepend:
  - Featherboard
  - PlaceholderAPI
  - HeadDatabase
commands:
  pack:
    usage: /<command>
    description: Opens your virtual backpack.